apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: dabloo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: html
        configMap:
          name: html-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-configmap
  namespace: dabloo
data:
  index.html: |
    <html>
    <head>
      <title>Frontend</title>
    </head>
    <body>
      <h1>Frontend Application</h1>
      <p>Attempting to connect to MySQL backend...</p>
    </body>
    </html>  

